// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5ZpKoSf6MLqk5DzNFVoAjYNILv4q5d0k',
    appId: '1:28588991274:web:0e5ec636b3f868f8693453',
    messagingSenderId: '28588991274',
    projectId: 'day-07',
    authDomain: 'day-07.firebaseapp.com',
    storageBucket: 'day-07.appspot.com',
    measurementId: 'G-GC1R1FSS71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC95-0KLiw60wjywBtioQpfDSRYX6iTG9M',
    appId: '1:28588991274:android:2f02293622aa3ea5693453',
    messagingSenderId: '28588991274',
    projectId: 'day-07',
    storageBucket: 'day-07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDvJMg8NiQ9XvzkNw3Bhnbm86Q252FZuM',
    appId: '1:28588991274:ios:6bcda43633528d3c693453',
    messagingSenderId: '28588991274',
    projectId: 'day-07',
    storageBucket: 'day-07.appspot.com',
    iosClientId: '28588991274-1efti7a1miupjqiup5j1o1o0m97tu6ss.apps.googleusercontent.com',
    iosBundleId: 'com.example.exDay2',
  );
}
